# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/requirements.json
#
collections:
  - name: community.libvirt
  - name: containers.podman
