# vi: set ft=yaml.ansible :
# - name: Install depends
#   hosts: localhost
# pre_tasks:
#   # https://www.redhat.com/en/blog/linux-golden-homelab-rhel
#   - name: ""
#     block:
#       - when: false
#         ansible.builtin.package:
#           name:
#             - cockpit-compose.noarch
#             - osbuild-composer
#             - composer-cli
#             - cockpit
#             - cockpit-composer
#       - ansible.builtin.systemd:
#           name:
#             - osbuild-composer.socket
#             - cockpit
#             - cockpit.socket
#           enabled: true
#           state: started
- name: Build Image.
  tasks:
    - name: Generate Compose Project
      block:
        - ansible.builtin.set_fact:
            bootc_templates:
              config:
                content: "{{ lookup('template', 'bootc.toml.j2' ) }}"
                dest: "{{ artifacts.bootc }}/config.toml"
              compose:
                content: "{{ lookup('template', 'bootc-compose.yaml.j2' ) }}"
                dest: "{{ artifacts.bootc }}/compose.yaml"
              script:
                content: "{{ lookup('template', 'bootc.sh.j2') }}"
                dest: "{{ artifacts.bootc }}/script.sh"
            bootc_output: "{{ artifacts.bootc_output }}/qcow/disk.qcow2"
        - ansible.builtin.stat:
            path: "{{ bootc_output }}"
          register: bootc_stat
        - ansible.builtin.copy:
            dest: "{{ item.value.dest }}"
            content: "{{ item.value.content }}"
          with_dict: "{{ bootc_templates }}"
    - name: Do build
      when: not bootc_output.stat.exists
      block:
        - community.docker.docker_compose_v2:
            files: ./compose.yaml
            project_src: "{{ bootc_dir }}"
            wait: true
            pull: true
            state: present
        - community.docker.docker_compose_v2_exec:
            files: ./compose.yaml
            project_src: "{{ bootc_dir }}"
            command: "{{ bootc.script.content }}"
        - community.docker.docker_compose_v2:
            files: ./compose.yaml
            project_src: "{{ bootc_dir }}"
            wait: false
            state: stopped
    - name: Move build results into the Image Directory
      ansible.builtin.copy:
        src: "{{ artifacts.bootc_output }}/qcow/disk.qcow2"
        dest: "{{ artifacts.images }}/{{ domain.name }}.qcow2"
