# vi: set ft=yaml.ansible :
- name: Customize with `virt-customize`.
  when: domain.image
  block:
    - name: Generate the customization script
      ansible.builtin.set_fact:
        virt_customize_script: "{{ lookup('template', './libvirt/customize.sh.j2') }}"
    - ansible.builtin.copy:
        content: '{{ virt_customize_script }}'
        dest: '{{ artifacts.templated }}/customize-{{ domain.name }}.sh'
    - name: Debug
      ansible.builtin.debug:
        var: virt_customize_script
    - name: Run the customization script
      become: true
      ansible.builtin.shell: "{{ virt_customize_script }}"
