# vi: set ft=yaml.ansible :
- name: Include Domain Context.
  ansible.builtin.include_tasks: ../context.yaml
- name: Inspect running domains.
  community.libvirt.virt:
    command: list_vms
    state: running
  register: domains_running
- name: Destroy VM
  when: domain.name in domains_running.list_vms
  community.libvirt.virt:
    command: destroy
    name: '{{ domain.name }}'
- name: Inspect Destroyed Domains
  community.libvirt.virt:
    command: list_vms
    state: shutdown
  register: domains_destroyed
- name: Undefine VM
  when: domain.name in domains_destroyed.list_vms
  community.libvirt.virt:
    command: undefine
    name: '{{ domain.name }}'
- name: Cleanup Image
  ansible.builtin.file:
    path: '{{ storage }}'
    state: absent
