# vi: set ft=toml :

[[customizations.user]]
name = "{{ libvirt.ansible.username }}"
password = "{{ libvirt.ansible.username }}"
key = "{{ domain.init.user.sshpubkey }}"
groups = ["wheel"]


[[customizations.user]]
name = "{{ domain.init.user.username }}"
password = "{{ domain.init.user.username }}"
key = "{{ domain.init.user.sshpubkey }}"
groups = ["wheel"]


[[cusomizations.files]]
path = "/etc/systemd/system-firstboot-single.service"
data = "[[

]]"

