# vi: set ft=yaml.ansible :
# NOTE(acederberg): This is where all of the common variables should be defined.
#                   This also includes setup for the assets directories, etc.
- name: Establish Facts
  block:
    - ansible.builtin.set_fact:
        artifacts_dir: "{{ inventory_dir }}/.artifacts"
    - ansible.builtin.set_fact:
        artifacts:
          base: "{{ artifacts_dir }}"
          images: "{{ artifacts_dir }}/images"
          templated: "{{ artifacts_dir }}/templated"
          bootc: "{{ artifacts_dir }}/bootc"
          bootc_outputs: "{{ artifacts_dir }}/bootc/outputs"
          ssh: "{{ artifacts_dir }}/ssh"
    - ansible.builtin.file:
        state: directory
        path: "{{ item.value }}"
        recurse: true
        owner: ansible
        group: ansible
        mode: '1700'
      with_dict: "{{ artifacts }}"
