# vi: set ft=yaml.ansible :
- name: Set variables
  block:
    - ansible.builtin.set_fact:
        image: domain.image
        filename: "{{ domain.image.src | urlsplit('path') |  split('/') | last }}"
    - ansible.builtin.set_fact:
        dest_local: "{{ libvirt.images_dir }}/{{ filename }}"
        dest_qemu: "/var/lib/libvirt/images/{{ filename }}"
- name: Download `{{ domain.name }}`
  ansible.builtin.get_url:
    url: '{{ domain.image.src }}'
    dest: '{{ dest_local }}'
    checksum: '{{ domain.image.checksum }}'
- name: Provide the Image to Qemu
  become: true
  ansible.builtin.copy:
    src: '{{ dest_local }}'
    dest: '{{ dest_qemu }}'
    owner: qemu
    group: qemu
    mode: '0640'
- name: Resize cloud image
  when: domain.image.kind == "cloud"
  block:
    - block:
        - name: Check size of `{{ domain.name }}` cloud image.
          block:
            - ansible.builtin.shell: |
                qemu-img measure \
                  {dest_qemu} \
                  --output=json \
                | jq '.["fully-allocated"]'
              register: image_size_sh
              become: true
            - ansible.builtin.debug:
                var: image_size_sh
            - ansible.builtin.set_fact:
                image_size_desired: '{{ domain.image.desired_size | human_to_bytes }}'
                image_size: '{{ image_size_sh.stdout | int }}'
            - ansible.builtin.set_fact:
                image_size_diff: '{{ image_size_desired - image_size }}'
            - ansible.builtin.debug:
                var: image_size_diff
        - name: Resize image `{{ dest_qemu }}` for `{{ domain.name }}`.
          when: image_size_diff > 0
          become: true
          ansible.builtin.shell: qemu-img resize {{ dest_qemu }} +{{ image_size_diff }}
          register: image_resize_sh
        - ansible.builtin.debug:
            var: image_resize_sh
    - name: Customize
      block:
        - name: Generate the customization script
          ansible.builtin.set_fact:
            virt_customize_script: "{{ lookup('template', './libvirt/customize.sh.j2') }}"
        - name: Debug
          ansible.builtin.debug:
            var: virt_customize_script
        - name: Run the customization script
          become: true
          ansible.builtin.shell: "{{ virt_customize_script }}"
