# vi: set ft=yaml.ansible :
- hosts: localhost
  tasks:
    - name: Templated
      block:
        - ansible.builtin.set_fact:
            templated_dir: '{{ inventory_dir }}/.templated'
        - ansible.builtin.file:
            path: '{{ templated_dir }}'
            state: directory
- name: Setup Libvirt Network
  hosts: localhost
  pre_tasks:
    # NOTE(acederberg): Because of absolute stupidity, it is not possible to
    #                   do this stuff in a virtual environment.
    #
    #                   See:
    #
    #                   - https://github.com/ansible/ansible/issues/64689#issuecomment-552948004
    - name: Get `libvirt` Deps
      when: ansible_python_interpreter == "/usr/bin/python3"
      block:
        - name: Make sure that 'libvirt-devel' is installed.
          become: true
          ansible.builtin.dnf:
            name: libvirt-devel
            state: present
            update_cache: true
        - name: Make sure that 'libvirt-python' is installed.
          ansible.builtin.pip:
            name: libvirt-python
            state: present
        - name: Ensure `virt-customize`.
          ansible.builtin.package:
            name:
              - libguestfs-tools-c
              - bootc-image-builder
            state: present
  tasks:
    - name: Declare Network
      community.libvirt.virt_net:
        command: define
        name: "{{ libvirt.network.name }}"
        xml: "{{ lookup('template', 'libvirt/network.xml.j2') }}"
    - name: Start Network
      community.libvirt.virt_net:
        command: start
        name: "{{ libvirt.network.name }}"
        autostart: true
# NOTE(acederberg): Generate SSH keys for ansible, set up hostnames, and verify connectivity.
- name: Configure host
  hosts: localhost
  tasks:
    - name: Generate an sshkey for ansible
      block:
        - ansible.builtin.set_fact:
            ansible_sshkeys_dir: "{{ inventory_dir }}/.ssh"
        - ansible.builtin.set_fact:
            ansible_sshkeys: "{{ ansible_sshkeys_dir }}/ansible"
        - ansible.builtin.stat:
            path: "{{ ansible_sshkeys_dir }}"
          register: ansible_sshkeys_dir_status
        - ansible.builtin.shell: mkdir --parents {{ ansible_sshkeys_dir }}
          when: not ansible_sshkeys_dir_status.stat.exists
        - ansible.builtin.stat:
            path: "{{ ansible_sshkeys }}"
          register: ansible_sshkeys_stat
        - name: Create Keypair
          when: not ansible_sshkeys_stat.stat.exists
          community.crypto.openssh_keypair:
            path: "{{ ansible_sshkeys }}"
            mode: "0440"
            type: ed25519
            state: present
          register: ansible_sshkeys
        - name: Debug
          ansible.builtin.debug:
            var: ansible_sshkeys
- name: Create Virtual Machines
  hosts: localhost
  tasks:
    - name: Create Images Directory
      block:
        - ansible.builtin.stat:
            path: "{{ libvirt.images_dir }}"
          register: image_dir
        - name: Create Images Dir
          when: not image_dir.stat.exists
          ansible.builtin.shell: mkdir --parents {{ libvirt.images_dir }}
    - name: Download and Customize Images
      ansible.builtin.include_tasks: virt-customize.yaml
      loop: '{{ libvirt.domains }}'
      loop_control:
        loop_var: domain
    - name: Start VMs
      ansible.builtin.include_tasks: virt-up.yaml
      loop: '{{ libvirt.domains }}'
      loop_control:
        loop_var: domain
        # NOTE(acederberg): save for later, disk only setup continuation
        # - name: Complete the install steps, Eject bootable media
        #   hosts: localhost
        #   tasks:
        #     - name: Complete install steps
- name: Complete Test Seup
  hosts: localhost
  tasks:
    - ansible.builtin.include_tasks: virt-finalize.yaml
