# vi: set ft=yaml.ansible :
# DESKTOP CUSTOMIZATION
- name: Set Context
  hosts: localhost
  tasks:
    - ansible.builtin.include_tasks:
        file: ./testing/context.yaml
    - ansible.builtin.set_fact:
        gnome_background_properties: /usr/share/gnome-background-properties
        dconf_local_d: /etc/dconf/db/local.d
        wallpapers_dir: /usr/local/share/backgrounds/
- name: Configure Backgrounds
  hosts: localhost
  tasks:
    - name: Add the default wallpapers to the system.
      block:
        - name: Copy Wallpapers into Shared.
          become: true
          ansible.builtin.copy:
            src: '{{ backgrounds.directory }}'
            dest: '{{ wallpapers_dir }}'
        - ansible.builtin.find:
            paths: '{{ wallpapers_dir }}'
          register: background_paths
        - ansible.builtin.set_fact:
            backgrounds_xml: '{{ lookup("template", "./templates/backgrounds.xml.j2") }}'
        - ansible.builtin.copy:
            content: '{{ backgrounds_xml }}'
            dest: '{{ artifacts.templated }}/backgrounds.xml'
        - name: Render Destops XML.
          become: true
          ansible.builtin.copy:
            content: '{{ backgrounds_xml }}'
            dest: '{{ gnome_background_properties }}/custom.xml'
    - name: Set the default wallpaper for the desktop.
      block:
        - ansible.builtin.set_fact:
            background_conf: '{{ lookup("template", "./templates/00-backgrounds.conf.j2" ) }}'
        - ansible.builtin.copy:
            content: '{{ background_conf }}'
            dest: '{{ artifacts.templated }}/background.conf'
        - become: true
          ansible.builtin.copy:
            content: '{{ background_conf }}'
            dest: '{{ dconf_local_d }}/00-background'
    - name: Set the default wallpaper for the homescreen.
      block:
        - ansible.builtin.set_fact:
            screensaver_conf: '{{ lookup("template", "./templates/01-screensaver.conf.j2") }}'
        - ansible.builtin.copy:
            content: '{{ screensaver_conf }}'
            dest: '{{ artifacts.templated }}/screensaver.conf'
        - become: true
          ansible.builtin.copy:
            content: '{{ screensaver_conf }}'
            dest: '{{ dconf_local_d }}/01-screensaver'
    - name: Restart `dconf`.
      become: true
      ansible.builtin.shell: "dconf update"
