- name: Build Lua
  hosts:
    - debian
    - redhat
- name: Build Neovim
  hosts:
    - debian
    - redhat
  remote_user: "{{ user.username }}"
  tasks:
    - name: Clone the repo
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        clone: yes
        dest: "{{ user.homedir }}/Ansible/Build/Neovim"
        version:
        depth: 1

#     - name: Make
#       ansible.builtin.
# - name: Build Kitty
#   hosts: all
#   remote_user: "{{ user.username }}"
#   tasks:
#     - name: Clone the repo
