# vi: set ft=yaml.ansible :
- name: Define Destination for all Ansible Assets.
  ansible.builtin.set_fact:
    artifacts_dir: "/home/{{ ansible_user_id }}/.artifacts"
- name: Define Ansible Assets Subdirs.
  ansible.builtin.set_fact:
    artifacts:
      base: "{{ artifacts_dir }}"
      repos: "{{ artifacts_dir }}/repos"
      templated: "{{ artifacts_dir }}/templated"
      backgrounds: "{{ artifacts_dir }}/templated/backgrounds"
- name: "Instantiate Ansible Assets Dirs."
  ansible.builtin.file:
    state: directory
    mode: "1700"
    path: "{{ item.value }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_dict: "{{ artifacts }}"
