# vi: set ft=yaml.ansible :
- name: "Create the Ansible Directory"
  hosts: debian
  remote_user: "{{ user.username }}"
  tasks:
    - name: Prepare the ansible directory.
      ansible.builtin.shell: "mkdir --parent {{ user.homedir }}/Ansible/Build"
- name: Update and Upgrade, Required Deps
  become: true
  hosts: all
  tasks:
    - name: Apt Update
      ansible.builtin.shell: apt update
      become: true
    - name: Apt Upgrade
      ansible.builtin.shell: apt upgrade --yes
      become: true
    - name: Apt Install Required
      become: true
      apt:
        name:
          - git
          - python3-pip
          - python3-venv
          - curl
          - cmake
          - ca-certificates
        state: latest
        update_cache: true
- name: Add Docker and Docker Compose
  hosts: debian
  become: true
  tasks:
    - name: Create keyring directory
      ansible.builtin.shell: install -m 0755 -d /etc/apt/keyrings
    - name: Download the GPG key
      ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - name: Set permissions on the key
      ansible.builtin.shell: sudo chmod a+r /etc/apt/keyrings/docker.asc
    - name: Add Docker Repository
      ansible.builtin.shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Update apt and install docker-ce
      apt:
        state: latest
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Install Docker Module for Python
      pip:
        name: docker
- name: Add Quarto
  hosts: all
  remote_user: "{{ user.username }}"
  tasks:
    - name: Get Quarto tarball
      ansible.builtin.get_tarball:
        url: https://github.com/quarto-dev/quarto-cli/releases/download/v1.8.24/quarto-1.8.24-linux-amd64.tar.gz
        checksum: 6b83c1c9b6f2ce6454798b42260bd2ee184551d74debe817b8aaf28b09ac22d0
        dest: "{{ user.homedir }}/Ansible/quarto.tar"
    - name: Untar Quarto
      become: true
      ansible.builtin.unarchive:
        creates: "/opt/quarto"
        dest: "/opt/quarto"
        src: "{{ user.homedir }}/Ansible/quarto.tar"
    - name: Quarto Symlink
      become: true
      ansible.builtin.shell: ln -s /opt/quarto/bin/quarto /bin/quarto
- name: Add NVM
  hosts: all
  tasks:
    - name: Get NVM Installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/refs/tags/v0.40.3/install.sh
        checksum: 2d8359a64a3cb07c02389ad88ceecd43f2fa469c06104f92f98df5b6f315275f
        dest: "{{ user.homedir }}/ansible/install-nvm.sh"
    - name: Run NVM Installer
      if: ""
      ansible.builtin.shell: bash "{{ user.homedir }}/ansible/install-nvm.sh"
- name: Add PyEnv
  hosts: all
  tasks:
    - name: Get PyEnv Installer
      ansible.builtin.git:
        repo: https://github.com/pyenv/pyenv.git
        clone: yes
        dest: "{{ user.homedir }}/.pyenv"
        depth: 1
        version: v2.6.8
